version: '3.8'

services:
  ethereum-pos:
    image: ethereum-pos
    volumes:
      - ./ganache_data:/usr/app/ganache_data
    ports:
      - "8545:8545"
      - "8546:8546"
    restart: unless-stopped
